export const songs1 = [
  {
    id: 1,
    title: "Aadat",
    url: "https://www.youtube.com/watch?v=NW44qHihuy0",
    lyrics: "https://www.youtube.com/watch?v=YQ5-eVFI_Hw",
    chords: ["C#m B A B"],
    strumming: "D UDUD UDUD DU",
    img: "https://i.ytimg.com/vi/NW44qHihuy0/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBEi4ThSNWsMKlFc3oith9IX4wtFA",
  },
  {
    id: 2,
    title: "Zara Sa",
    url: "https://www.youtube.com/watch?v=eagqhLCQQY0&t=23s",
    lyrics: "https://www.youtube.com/watch?v=gYpHek_hW1w",
    chords: ["Bm G A Bm", "G A Bm", "D A G A", "D A Bm"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/lkkjeXoiDqg/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC2DKrGQ5A2rdVutynSz_uWNWWUtQ",
  },
  {
    id: 3,
    title: "Woh Lamhe",
    url: "https://www.youtube.com/watch?v=_EvGL6TgdRY",
    lyrics: "https://www.youtube.com/watch?v=3DYIk5oN4KA",
    chords: ["G#m F# E F#"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/_EvGL6TgdRY/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAJRCsoOQVQWwBF7eHllD5ETBkg3w",
  },
  {
    id: 4,
    title: "Ae Dil Hai Mushkil - Capo 1st",
    url: "https://www.youtube.com/watch?v=mVcThoh052E",
    lyrics: "https://www.youtube.com/watch?v=d0EA2ILnkF0",
    chords: ["Dm Gm Bb A Dm", "Dm C Bb Am"],
    strumming: "DDU UDU",
    img: "https://i.ytimg.com/vi/mVcThoh052E/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCvEMRdwPoSZ9NPnXDWiNmN3HiA6g",
  },
  {
    id: 5,
    title: "Mujhe Peene Do - Capo 6th",
    url: "https://www.youtube.com/watch?v=DayTEy1wlXU",
    lyrics: "https://www.youtube.com/watch?v=ZnXHvKlUJ34",
    chords: ["Am G F E ", "Am C G F-Dm G E"],
    strumming: "D DUDU",
    img: "https://i.ytimg.com/vi/DayTEy1wlXU/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD-ALlTX6pX9063SE0XxQW0z4WPPg",
  },
  {
    id: 6,
    title: "Teri Yaadon Mein",
    url: "https://www.youtube.com/watch?v=Sy2N6fMI_Qo",
    lyrics: "https://www.youtube.com/watch?v=PBPDF44KwCE",
    chords: ["F# Bm", "G A G F#"],
    strumming: "D UDUD UDUD DU",
    img: "https://i.ytimg.com/vi/Sy2N6fMI_Qo/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDRJlsIEf-Ephw7Gx7cNWHuwm6I5g",
  },
  {
    id: 7,
    title: "Tu Hi Meri Shab Hai",
    url: "https://www.youtube.com/watch?v=X3yC8uaFSr4",
    lyrics: "https://www.youtube.com/watch?v=NaDgLnhRgtg",
    chords: ["Em F Am", "G F Am"],
    strumming: "D UDUD UDUD DU",
    img: "https://i.ytimg.com/vi/X3yC8uaFSr4/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAqRxgRYeXG9mTwgCcimcJfdRV55w",
  },
  {
    id: 8,
    title: "Bol Do Na Zara",
    url: "https://www.youtube.com/watch?v=YdZd9aohyYI&t=232s",
    lyrics: "https://www.youtube.com/watch?v=f9_C8J4gqzQ",
    chords: ["Bm G F#m G", "Bm G Em A"],
    strumming: "D DUDU",
    img: "https://i.ytimg.com/vi/YdZd9aohyYI/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCPyQ0y4zQwCW1Qx0zt_3JH7swEAQ",
  },
  {
    id: 9,
    title: "Gulaabi Aankhein",
    url: "https://www.youtube.com/watch?v=CaoH1HatRAE",
    lyrics: "https://www.youtube.com/watch?v=oFQdKo2rrf0",
    chords: ["Am G F E", "E F G F E"],
    strumming: "D UDUD UDUD DU",
    img: "https://i.ytimg.com/vi/CaoH1HatRAE/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDwsV9SmKm6oo-VycugDsyHw-bbrQ",
  },
  {
    id: 10,
    title: "Tum Hi Ho",
    url: "https://www.youtube.com/watch?v=h07HKdiCDq0&t=526s",
    lyrics: "https://www.youtube.com/watch?v=asxmdFaIock",
    chords: ["Em Am D Bm Em"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/h07HKdiCDq0/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC8ALmO15pzUHxJVISEZl5Xk2edIw",
  },
  {
    id: 11,
    title: "Tera Mera Rishta",
    url: "https://www.youtube.com/watch?v=Pz4c1N4PUb8",
    lyrics: "https://www.youtube.com/watch?v=S8BHBts-rgk",
    chords: ["Em D C D"],
    strumming: "D D UUD DDU",
    img: "https://i.ytimg.com/vi/Pz4c1N4PUb8/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBZ3RNYYM8S-ZYT0Ho_6RX7NEYTTg",
  },
  {
    id: 12,
    title: "Kya Mujhe Pyar Hai",
    url: "https://www.youtube.com/watch?v=edRc1CfwSIo",
    lyrics: "https://www.youtube.com/watch?v=Gg6NMU4ivXM",
    chords: ["F#m E D E", "A E F#m E"],
    strumming: "D UDUD UDUD DU",
    img: "https://i.ytimg.com/vi/edRc1CfwSIo/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAAf7tLYtwNbxYwZuFeeMkJgfa_-w",
  },
  {
    id: 13,
    title: "Pani Da Rang",
    url: "https://www.youtube.com/watch?v=Qqm8xmgmlWc",
    lyrics: "https://www.youtube.com/watch?v=2kgEc6oH9J0",
    chords: ["Em D C D Em", "C D Em"],
    strumming: "D UUD UUD DU",
    img: "https://i.ytimg.com/vi/Qqm8xmgmlWc/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAfcmzL_18XC1GrLSi5Zra84yNS0w",
  },
  {
    id: 14,
    title: "Haal Ae Dil",
    url: "https://www.youtube.com/watch?v=Htkwc5Vqj7o",
    lyrics: "https://www.youtube.com/watch?v=acdKE2hja7w",
    chords: ["Am G F Em", "Am C G F Em"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/Htkwc5Vqj7o/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA7bQ7PYxkWdhsRGbg56M4tLs7DyA",
  },
  {
    id: 15,
    title: "Kabhi Jo Badal",
    url: "https://www.youtube.com/watch?v=wzVHPqKiQuI",
    lyrics: "https://www.youtube.com/watch?v=11uuhJBllOQ",
    chords: ["Cm Bb Ab Bb", "Cm Gm Bb", "Fm Bb Ab"],
    strumming: "DD UUD DDU",
    img: "https://i.ytimg.com/vi/wzVHPqKiQuI/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2GcMSVlpwqxFy5F6hDh3IZsPHQQ",
  },
  {
    id: 16,
    title: "Tere Bin",
    url: "https://www.youtube.com/watch?v=Fqe1r3_RYws",
    lyrics: "https://www.youtube.com/watch?v=c6BuSdEE3kU",
    chords: ["AmEmFEm", "AmGFAm", "AmDmG", "AmFG"],
    strumming: "D UUD UUD DU",
    img: "https://i.ytimg.com/vi/Fqe1r3_RYws/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCIGd_ke91xy75JscuoRDTVQM6HjQ",
  },
  {
    id: 17,
    title: "Chahun Main Ya Na",
    url: "https://www.youtube.com/watch?v=rGLPjnsJB5o",
    lyrics: "https://www.youtube.com/watch?v=U3aoGDjDI2s",
    chords: ["Am G F G", "C Am F G", "C Em F G C", "Am G F E"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/rGLPjnsJB5o/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAt8ypQGl3rGONkbpdpSnbzJoBhSA",
  },

  {
    id: 18,
    title: "Mujhko Barsaat Bana Lo",
    url: "https://www.youtube.com/watch?v=-c4kVcsHc1A",
    lyrics: "https://www.youtube.com/watch?v=q21aUQyFde8",
    chords: ["Bm G A Bm", "A G A G F#", "Bm G Bm G", "Bm D A G Bm"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/-c4kVcsHc1A/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB8jB_Fg1c51KyFQX0ywJV4TYVepg",
  },
  {
    id: 19,
    title: "Kabhi Toh Paas Mere Aao",
    url: "https://www.youtube.com/watch?v=vRUhpLyT1h4",
    lyrics: "https://www.youtube.com/watch?v=2c_43PKXxKk",
    chords: ["Am G F Am", "G Am F Am C", "C G F E"],
    strumming: "D D UUD DDU",
    img: "https://i.ytimg.com/vi/vRUhpLyT1h4/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBSZP5fSRyktdhk1KoufSBFYnDYRA",
  },
  {
    id: 20,
    title: "Filhaal-2",
    url: "https://www.youtube.com/watch?v=NJHXCMtZbc0",
    lyrics: "https://www.youtube.com/watch?v=vzlyLJqxegA",
    chords: ["Am Dm G C"],
    strumming: "D D UUD DDU",
    img: "https://i.ytimg.com/vi/NJHXCMtZbc0/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBQJHghFQINJA7p4DMaGzhSeq84KQ",
  },
];

export const songs2 = [
  {
    id: 21,
    title: "Teri meri kahaani",
    url: "https://www.youtube.com/watch?v=QpwPIOBDSjg",
    lyrics: "https://www.youtube.com/watch?v=hcJl3ovWsYg",
    chords: [
      "D#m G#m D#m G#m C#",
      "D#m B C#",
      "D#m C# B G#m",
      "F#, A#m, B, C#",
    ],
    strumming: "D UDUD UDUD UDU",
    img: "https://i.ytimg.com/vi/QpwPIOBDSjg/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB7RKaIw1L17kn4XJ5WNg0UawXLZg",
  },
  {
    id: 22,
    title: "Bekhayali",
    url: "https://www.youtube.com/watch?v=9H1-hENz5rs",
    lyrics: "https://www.youtube.com/watch?v=K9w6UBZOn5o",
    chords: ["Am F G Em - Dm F Am Em", "Am G F G"],
    strumming: "D DUDU",
    img: "https://i.ytimg.com/vi/9H1-hENz5rs/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCqfryQEdbOLTsJYkYnUxonuTb2HQ",
  },
  {
    id: 23,
    title: "Milne Hai Mujhse Aayi",
    url: "https://www.youtube.com/watch?v=LDU_4CciboI",
    lyrics: "https://www.youtube.com/watch?v=VVFDArjvalE&t=5s",
    chords: ["Bm A G F#", "D A G A", "Bm A G"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/LDU_4CciboI/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAIsKEYfeBAnxoVmovRC_ZNcqExag",
  },
  {
    id: 24,
    title: "Sun Raha Hai Na Tu - Capo 3rd",
    url: "https://www.youtube.com/watch?v=KPATARVaY3k",
    lyrics: "https://www.youtube.com/watch?v=pyzjQz209Xo",
    chords: ["Am F G Em G", "Am D Am D", "Am G F Dm C", "F G Em F C", "Dm C-G"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/KPATARVaY3k/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBCFaFQEtGSAW4VWM12qvKpbsNFHg",
  },
  // {
  //   id: 25,
  //   title: "Tujhe Kitna Chahne lage",
  //   url: "https://www.youtube.com/watch?v=LK7hhMgCTeA",
  //   lyrics: "https://www.youtube.com/watch?v=xroMi3fFjys",
  //   chords: ["E F# D#m G#m C#m F#"],
  //   strumming: "D D UDUD DDU",
  //   img: "https://i.ytimg.com/vi/LK7hhMgCTeA/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC8WGSVJDKV9zuB4utCbQtKr4vxfg",
  // },
  {
    id: 25,
    title: "Tujhe Kitna Chahne lage - Capo 3rd",
    url: "https://www.youtube.com/watch?v=-qgPY7dHDJQ",
    lyrics: "https://www.youtube.com/watch?v=xroMi3fFjys",
    chords: ["Am D C D G", "C D Em Bm C D Em "],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/-qgPY7dHDJQ/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBkz_F6jtYozSCICjrsshtJAL8piw",
  },
  {
    id: 26,
    title: "Bulleya",
    url: "https://www.youtube.com/watch?v=DKYKlgGO4mQ",
    lyrics: "https://www.youtube.com/watch?v=bFn62eG2WYA",
    chords: ["Dm Bb-Eb A ", "Dm Bb G C Bb-Dm"],
    strumming: "DDU UDU",
    img: "https://i.ytimg.com/vi/DKYKlgGO4mQ/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBRQIIAKAzlfW8WJgF_AKVGM81ObQ",
  },
  {
    id: 27,
    title: "Har Kisi Ko Nahi Milta",
    url: "https://www.youtube.com/watch?v=Ypfk97taiKk&t=629s",
    lyrics: "https://www.youtube.com/watch?v=WtgGzgcNHNk",
    chords: ["A# D# A# D# G#-A# G# F# G#", "A# G# B A#-A# D# F# A#"],
    strumming: "D UDUD UDUD DU",
    img: "https://i.ytimg.com/vi/Ypfk97taiKk/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDEEr2IbuycMACCOXlffTkdche_xQ",
  },
  {
    id: 28,
    title: "Mere Mehboob Qayamat Hogi",
    url: "https://www.youtube.com/watch?v=nTxQJSUH2FY",
    lyrics: "https://www.youtube.com/watch?v=K9YWU0GB_es",
    chords: ["Bm A Em F#m G A Bm", "Bm-Em F#m Bm", "D A Em Bm A Bm"],
    strumming: "D DU UDU",
    img: "https://i.ytimg.com/vi/nTxQJSUH2FY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCiQ9Wt9yMN0jCore4rWQok-7HDsQ",
  },
  {
    id: 29,
    title: "Humnava Mere",
    url: "https://www.youtube.com/watch?v=M7xe9JzLDkA",
    lyrics: "https://www.youtube.com/watch?v=-U_Q-UxtX-M",
    chords: ["Em D C D Em", "Em Am D-Bm", "Em D C Bm C D"],
    strumming: "DD UUD DDU",
    img: "https://i.ytimg.com/vi/M7xe9JzLDkA/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBTJPF0W_hOBlfb4UA1TpkrbKVXiA",
  },
  {
    id: 30,
    title: "Khamoshiyan",
    url: "https://www.youtube.com/watch?v=Te71caGBmUk",
    lyrics: "https://www.youtube.com/watch?v=qN88U6ZqR-4",
    chords: ["Dm F Am Gm", "Bb C A", "Bb C F AmDm", "Dm Gm C F"],
    strumming: "D DUDU",
    img: "https://i.ytimg.com/vi/Te71caGBmUk/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCD4NhIh1_CxSDSFYEvRNTMgG5xQg",
  },
  {
    id: 31,
    title: "Hamari Adhuri Kahani",
    url: "https://www.youtube.com/watch?v=CvREKj8Evnc&t=327s",
    lyrics: "https://www.youtube.com/watch?v=SRkfDLZxSww",
    chords: ["C F G/Bb C E", "Am F G C"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/CvREKj8Evnc/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLANnGrrj8jCK6wqxfyaqnJQ8vDanw",
  },

  {
    id: 32,
    title: "Kesariya",
    url: "https://www.youtube.com/watch?v=E3XqfI_jmbM",
    lyrics: "https://www.youtube.com/watch?v=W1S9AbHpWFY",
    chords: ["C Em F G", "F C F C-G"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/E3XqfI_jmbM/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBfU7g0JfOZbRMHNq6BatRtPYqaMw",
  },
  {
    id: 33,
    title: "Dil Ko Karar Aaya - Capo 4th",
    url: "https://www.youtube.com/watch?v=87gv9coTbYo",
    lyrics: "https://www.youtube.com/watch?v=Jm9tuXUawxk",
    chords: ["Em G D C-D"],
    strumming: "D D D UUD DDU",
    img: "https://i.ytimg.com/vi/87gv9coTbYo/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD9ag_g17bIMSbttMW6HzOgfQeQ5g",
  },
  {
    id: 34,
    title: "Baarish - Capo 3rd",
    url: "https://www.youtube.com/watch?v=9erEl9-sdOo",
    lyrics: "https://www.youtube.com/watch?v=QWkhWsMTugA",
    chords: ["Em D Am Bm C", "Em D C B Em", "Bm A C D Em"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/9erEl9-sdOo/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCqOYVYSVzDtTFjjHJmWOI9qiqzQQ",
  },
  {
    id: 35,
    title: "Khairiyat - Capo 3rd",
    url: "https://www.youtube.com/watch?v=LUjx5vh5Id8",
    lyrics: "https://www.youtube.com/watch?v=wGAhDeobiac",
    chords: ["Am G F", "Am F G E", "Dm F G E", "C G E"],
    strumming: "DUCU UCU",
    img: "https://i.ytimg.com/vi/LUjx5vh5Id8/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCe0cbI1MvnbunDqT8KTyWUjo4uQQ",
  },

  {
    id: 36,
    title: "Jitni Dafa - Capo 1st",
    url: "https://www.youtube.com/watch?v=L7cgv9KDTaw",
    lyrics: "https://www.youtube.com/watch?v=EsrenIAGrzo",
    chords: ["Am C G E-Am F G Am", "Am F C Dm G Am"],
    strumming: "DUCU UCU",
    img: "https://i.ytimg.com/vi/L7cgv9KDTaw/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAFSMxLFSBRKkCxtFzNQqAcvNicdw",
  },
  {
    id: 37,
    title: "Shayad - Capo 1st",
    url: "https://www.youtube.com/watch?v=d2u_TKR7btc",
    lyrics: "https://www.youtube.com/watch?v=OnAyBZQc1vk",
    chords: ["Em G D-Bm C G"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/d2u_TKR7btc/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBxhVf3bMTmUO6_f0uaZHpLicJ6iQ",
  },
  {
    id: 38,
    title: "Janam Janam",
    url: "https://www.youtube.com/watch?v=5tDcfILfIA0",
    lyrics: "https://www.youtube.com/watch?v=tuCOiHoJruI",
    chords: ["Bm Em A D G C F# G E F#"],
    strumming: "D DUDU",
    img: "https://i.ytimg.com/vi/UoF6pin59yc/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBWZbFoH1fBkh2W5ZkuS3Po3w29nw",
  },
  {
    id: 39,
    title: "Tum Hi Aana",
    url: "https://www.youtube.com/watch?v=aF3D7M0nsv0&t=599s",
    lyrics: "https://www.youtube.com/watch?v=dnGPhxd4P4s",
    chords: ["C Em", "Em D Bm C", "D Am C Em"],
    strumming: "DCU UCU",
    img: "https://i.ytimg.com/vi/aF3D7M0nsv0/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLArdju_w8j3oHn9YUB5S8hvHDEk3Q",
  },
  {
    id: 40,
    title: "Ye Jism Hai To Kya",
    url: "https://www.youtube.com/watch?v=iwSWMcyuiCw&t=283s",
    lyrics: "https://www.youtube.com/watch?v=zApYIJfX3nk",
    chords: ["Em D C D C Em"],
    strumming: "D D UUD DDU",
    img: "https://i.ytimg.com/vi/iwSWMcyuiCw/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD3t_faohmJwO8mKVSDQk_X8V_vSQ",
  },
  {
    id: 41,
    title: "Labon Ko",
    url: "https://www.youtube.com/watch?v=cU3DMjFWqac",
    lyrics: "https://www.youtube.com/watch?v=0OGguI0uDfE",
    chords: ["Am G F", "E F G F G F", "Am G F G"],
    strumming: "D UDUD UDUD DU",
    img: "https://i.ytimg.com/vi/cU3DMjFWqac/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB_XpX9wilW6zX1N4E0Bq4YY5TzQg",
  },

  {
    id: 42,
    title: "Mile Ho Tum Humko",
    url: "https://www.youtube.com/watch?v=Du1XMsVasdE&t=142s",
    lyrics: "https://www.youtube.com/watch?v=2qLgVd3ZyRo",
    chords: ["Am G F G-F Am Dm G F G Am"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/Du1XMsVasdE/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDkgVJZmrNSg71fjGRWGQgMo_U-Ug",
  },
  // {
  //   id: 42,
  //   title: "Uska Hi Banana - Capo 3rd",
  //   url: "https://www.youtube.com/watch?v=jo5h47K-0EE&t=134s",
  //   lyrics: "https://www.youtube.com/watch?v=x66LfjYJa2k",
  //   chords: ["Am G F E", "Am F G C", "Am Dm Em Am", "Am G F Em Am"],
  //   strumming: "D D UDUD DDU",
  //   img: "https://i.ytimg.com/vi/jo5h47K-0EE/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBFrVUahQt56NrSJYf9fpqojGbcCA",
  // },
  {
    id: 43,
    title: "Neele Neele Amber Par",
    url: "https://www.youtube.com/watch?v=UjchT8-Frcw",
    lyrics: "https://www.youtube.com/watch?v=sXdG1SbRd3A",
    chords: ["Dm C Bb A", "Dm C Dm-Bb A"],
    strumming: "DDU UDU",
    img: "https://i.ytimg.com/vi/UjchT8-Frcw/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBpNKcVyDfEodR44qEEZUe7ftEVeg",
  },
  {
    id: 44,
    title: "Man Mera",
    url: "https://www.youtube.com/watch?v=Uo0sBQS1to8&t=18s",
    lyrics: "https://www.youtube.com/watch?v=s2kx8UOqFOs",
    chords: ["C#m B A B"],
    strumming: "D UUD UUD DU",
    img: "https://i.ytimg.com/vi/Uo0sBQS1to8/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDLMFvDDouDNoLjfkuEedjLMZuqFg",
  },
  {
    id: 45,
    title: "Hai Apna Dil To Awara",
    url: "https://www.youtube.com/watch?v=IvDfwkGUErs",
    lyrics: "https://www.youtube.com/watch?v=Qc0GYPXENms",
    chords: ["G DC DC DG", "G C D CG", "G G C DG"],
    strumming: "DUCUDUCU",
    img: "https://i.ytimg.com/vi/IvDfwkGUErs/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAfSQtugyjBDcRJleG_3WKbbYSuhw",
  },
  {
    id: 46,
    title: "Sajni",
    url: "https://www.youtube.com/watch?v=P1RwldegG_c&t=514s",
    lyrics: "https://www.youtube.com/watch?v=P1RwldegG_c&t=514s",
    chords: ["G#m F# C#m D#m", "E F# G#"],
    strumming: "D UDUD UDUD DU",
    img: "https://i.ytimg.com/vi/P1RwldegG_c/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLADnxoqt2atJPmMMSbXa3BgA9K5Hw",
  },
  {
    id: 47,
    title: "Jee Le Zara",
    url: "https://www.youtube.com/watch?v=DNOOevrC730",
    lyrics: "https://www.youtube.com/watch?v=NQncvPWen0o",
    chords: ["Am G-F Dm F G", "F G Am"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/DNOOevrC730/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDItXEWjdDTmooIdVYIEgTsggxJ8w",
  },

  // {
  //   id: 47,
  //   title: "Tujhe Sochta Hu - Capo 3rd",
  //   url: "https://www.youtube.com/watch?v=UIWNmdroaSE",
  //   lyrics: "https://www.youtube.com/watch?v=6dpGCp3z-n8",
  //   chords: ["Am G F Am/E", "Am G-F Am/E"],
  //   strumming: "D D UDUD DDU",
  //   img: "https://i.ytimg.com/vi/UIWNmdroaSE/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC-T06IzNgk1a7UcU-kQqKXIDJoLw",
  // },
  {
    id: 48,
    title: "Hogaya Hai Tujhko - Capo 4th",
    url: "https://www.youtube.com/watch?v=yN-NYans-wA",
    lyrics: "https://www.youtube.com/watch?v=M_bBw50pRII",
    chords: ["Em C D B7 Em", "Em D Em-C Em", "Am Em-Em D Em"],
    strumming: "DDU/DU ",
    img: "https://i.ytimg.com/vi/yN-NYans-wA/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDEqc4NnA1pAXJz2Mqd8-QlVuQp2A",
  },
  {
    id: 49,
    title: "Main Dhoondne Ko Zamanae Me",
    url: "https://www.youtube.com/watch?v=iZDHhkCUcRA",
    lyrics: "https://www.youtube.com/watch?v=blkMNxQYCos",
    chords: ["Dm C Bb C", "Dm Am Bb C"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/iZDHhkCUcRA/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCWVGLNwof7GPGc987fV0-jewpbyg",
  },
  {
    id: 50,
    title: "Filhaal - Capo 3rd",
    url: "https://www.youtube.com/watch?v=cEGGXdON28M&t=8s",
    lyrics: "https://www.youtube.com/watch?v=9Csrfj8QZN4",
    chords: ["F Em Am"],
    strumming: "D D UUD DDU",
    img: "https://i.ytimg.com/vi/cEGGXdON28M/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD9M2Djknr5U138H84onDGIu5K0Vw",
  },
];

export const extras = [
  {
    id: 51,
    title: "How to do singing with guitar",
    url: "https://www.youtube.com/watch?v=Vqj2gCAJIfY",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/Vqj2gCAJIfY/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA2Y0HRnq915y33JrhQS827XbhHfQ",
  },
  {
    id: 52,
    title: "Tum Hi Ho - Lead",
    url: "https://www.youtube.com/watch?v=s2lvF0TrF2w",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/s2lvF0TrF2w/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDMxD8Ui8eReRos_1dPvVHG46PTmA",
  },
  {
    id: 53,
    title: "Janam Janam - Lead",
    url: "https://www.youtube.com/watch?v=PUAk1fhcJgk&t=195s",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/PUAk1fhcJgk/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDmqRzx02iGiwIxDFmvJ4K2NniUng",
  },
  {
    id: 54,
    title: "Game of Thrones - Theme song",
    url: "https://www.youtube.com/watch?v=u_1fqr5OCMU&t=57s",
    lyrics: "",
    chords: [""],
    strumming: "D DUDU",
    img: "https://i.ytimg.com/vi/u_1fqr5OCMU/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLARv6FMNSLRDLRrkkRa6bWphmm7kQ",
  },
  {
    id: 55,
    title: "Pirates of Carribbean - Theme",
    url: "https://www.youtube.com/watch?v=-3euwoOoenM&t=80s",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/-3euwoOoenM/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAhUyid7G0ERoAbAUyZTT6BWE8nsg",
  },
  {
    id: 56,
    title: "Gratitude Guitar Solo",
    url: "https://www.youtube.com/watch?v=z6FoVylAlNA",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/z6FoVylAlNA/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBY7RuFG7ExrA5Se3P7Va9qGKd4iA",
  },
  {
    id: 57,
    title: "Amin Toofani - Veer Kumar",
    url: "https://www.youtube.com/watch?v=HG0BPP-aCq8",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/HG0BPP-aCq8/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDHFs8G5Uqpei7M_6s2VInpN9orlQ",
  },

  {
    id: 58,
    title: "Ya Ali",
    url: "https://www.youtube.com/watch?v=QB6lnNwVWZE",
    lyrics: "https://www.youtube.com/watch?v=s05m-PbVYic",
    chords: ["Em Am D B7 - D Em C B7"],
    strumming: "D U D U DUDU",
    img: "https://i.ytimg.com/vi/QB6lnNwVWZE/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDEqAQRHxy7UwLXlWs-88COgLcO7w",
  },
  {
    id: 59,
    title: "O O Jane Jana",
    url: "https://www.youtube.com/watch?v=kV2SK6M9VOg",
    lyrics: "https://www.youtube.com/watch?v=JtAp4GnkMbE",
    chords: ["Am G F G Em"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/kV2SK6M9VOg/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBDyjbbERHKYRwmHYVM_jqpGKvm5Q",
  },
  {
    id: 60,
    title: "Maan Meri Jaan",
    url: "https://www.youtube.com/watch?v=iFzpQngfWLk&t=168s",
    lyrics: "https://www.youtube.com/watch?v=3RAoczaBVP8",
    chords: ["Em Am D F# B Em"],
    strumming: "DUDU",
    img: "https://i.ytimg.com/vi/iFzpQngfWLk/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCJDnVuHJ8I4RqWTVWPZn5SzlHM8Q",
  },
  {
    id: 61,
    title: "Inteha Ho Gayi",
    url: "https://www.youtube.com/watch?v=1JbdMBNiw7I",
    lyrics: "https://www.youtube.com/watch?v=4muKrzVo7bU",
    chords: ["Em Am D F# B Em"],
    strumming: "D DU UDU",
    img: "https://i.ytimg.com/vi/1JbdMBNiw7I/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDn4-0qedGh3r-d96vKokCuSG1mXA",
  },
];
