export const strumming = [
  {
    id: 0,
    title: "Strumming",
    url: "https://www.youtube.com/watch?v=fAs6jwQp9XU&t=246s",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/fAs6jwQp9XU/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBpj5pAsEm4f3h1ASldo9QsaRcpzg",
  },
];

export const songs1 = [
  {
    id: 1,
    title: "Aadat",
    url: "https://www.youtube.com/watch?v=NW44qHihuy0&t=267s",
    lyrics: "https://www.youtube.com/watch?v=DLN4yfKYTqE",
    chords: ["C#m B A B"],
    strumming: "D UDUD UDUD DU",
    img: "https://i.ytimg.com/vi/NW44qHihuy0/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBEi4ThSNWsMKlFc3oith9IX4wtFA",
  },
  {
    id: 2,
    title: "Zara Sa",
    url: "https://www.youtube.com/watch?v=eagqhLCQQY0&t=66s",
    lyrics: "https://www.youtube.com/watch?v=NvkTqQCift4",
    chords: ["Bm G A G", "G A Bm", "D A G A", "D A Bm"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/lkkjeXoiDqg/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC2DKrGQ5A2rdVutynSz_uWNWWUtQ",
  },
  {
    id: 3,
    title: "Woh Lamhe",
    url: "https://www.youtube.com/watch?v=_EvGL6TgdRY",
    lyrics: "https://www.youtube.com/watch?v=1DBhic8SSKs",
    chords: ["G#m F# E F#"],
    strumming: "D UUD UUD DU",
    img: "https://i.ytimg.com/vi/_EvGL6TgdRY/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAJRCsoOQVQWwBF7eHllD5ETBkg3w",
  },
  {
    id: 4,
    title: "Ae Dil Hai Mushkil - Capo 1st",
    url: "https://www.youtube.com/watch?v=mVcThoh052E",
    lyrics: "https://www.youtube.com/watch?v=d0EA2ILnkF0",
    chords: ["Dm Gm Bb A Dm", "Dm C Bb Am", "Dm Bb Gm C"],
    strumming: "DDU UDU",
    img: "https://i.ytimg.com/vi/mVcThoh052E/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCvEMRdwPoSZ9NPnXDWiNmN3HiA6g",
  },
  {
    id: 5,
    title: "Phir Mohabbat - Capo 3rd",
    url: "https://www.youtube.com/watch?v=D4cBpo5UlaU",
    lyrics: "https://www.youtube.com/watch?v=biiHl1rn4tw",
    chords: ["Am Em F Am", "Am Em F Em", "Dm Em Dm Em", "Am F E"],
    strumming: "DCU UCU",
    img: "https://i.ytimg.com/vi/D4cBpo5UlaU/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBDCDHi-Dbzvw5wX35jyzhcGdtxDA",
  },
  {
    id: 6,
    title: "Tujhe Sochta Hun - Capo 3rd",
    url: "https://www.youtube.com/watch?v=UIWNmdroaSE&t=130s",
    lyrics: "https://www.youtube.com/watch?v=0A6OfRb3IWM",
    chords: ["Am G F E/Am", "Am G F G", "Am Em F G"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/UIWNmdroaSE/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC-T06IzNgk1a7UcU-kQqKXIDJoLw",
  },
  {
    id: 7,
    title: "Dil Mein Ho Tum - Capo 4th",
    url: "https://www.youtube.com/watch?v=ezHyaI82V7w",
    lyrics: "https://www.youtube.com/watch?v=YL4_cwdKZBU",
    chords: ["Em D C G B", "Em C D Bm-G Bm C D", "Em D C D Em", "B C D B-G C"],
    strumming: "DUCD UUD DU",
    img: "https://i.ytimg.com/vi/ezHyaI82V7w/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBlGUUpmcp5ZkpUJWyHwITC8KmmzQ",
  },
  {
    id: 8,
    title: "Teri Yaadon Mein",
    url: "https://www.youtube.com/watch?v=Sy2N6fMI_Qo&t=112s",
    lyrics: "https://www.youtube.com/watch?v=PBPDF44KwCE",
    chords: ["F# Bm", "A G A F#", "Em-F# Em F#-Bm A G Em-F#"],
    strumming: "D UDUD UDUD DU",
    img: "https://i.ytimg.com/vi/Sy2N6fMI_Qo/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDRJlsIEf-Ephw7Gx7cNWHuwm6I5g",
  },
  {
    id: 9,
    title: "Tu Hi Meri Shab Hai",
    url: "https://www.youtube.com/watch?v=X3yC8uaFSr4",
    lyrics: "https://www.youtube.com/watch?v=k33ZV9sMeZ8",
    chords: ["Em F Am-Am G F Am", "G F Am", "E-Am E Am", "D C D Am G E Am"],
    strumming: "D UDUD UDUD DU",
    img: "https://i.ytimg.com/vi/X3yC8uaFSr4/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAqRxgRYeXG9mTwgCcimcJfdRV55w",
  },
  {
    id: 10,
    title: "Gulabi Aankhen",
    url: "https://www.youtube.com/watch?v=CaoH1HatRAE&t=100s",
    // lyrics: "https://www.youtube.com/watch?v=oFQdKo2rrf0",
    lyrics: "https://www.youtube.com/watch?v=aJ0k6xOiOOA",
    chords: ["Am G F E", "E F G F E"],
    strumming: "D UDUD UDUD DU",
    img: "https://i.ytimg.com/vi/CaoH1HatRAE/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDwsV9SmKm6oo-VycugDsyHw-bbrQ",
  },
  {
    id: 11,
    title: "Tum Hi Ho - Capo 1st",
    url: "https://www.youtube.com/watch?v=elLYyTJkjtg",
    lyrics: "https://www.youtube.com/watch?v=asxmdFaIock",
    chords: ["Em Am D Bm C", "Em Bm Am Em", "D G B C-D", "C Bm-Am Em"],
    strumming: "DCU UCU",
    img: "https://i.ytimg.com/vi/elLYyTJkjtg/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD1_h4QELkc_X4l7RESFxJSiz_5xw",
  },
  // {
  //   id: 12,
  //   title: "Kya Mujhe Pyar Hai",
  //   url: "https://www.youtube.com/watch?v=edRc1CfwSIo",
  //   lyrics: "https://www.youtube.com/watch?v=Gg6NMU4ivXM",
  //   chords: ["F#m E D E", "A E F#m E"],
  //   strumming: "D UDUD UDUD DU",
  //   img: "https://i.ytimg.com/vi/edRc1CfwSIo/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAAf7tLYtwNbxYwZuFeeMkJgfa_-w",
  // },
  {
    id: 12,
    title: "Kya Mujhe Pyar Hai - Capo 2nd",
    url: "https://www.youtube.com/watch?v=PkjnF_0YxNQ",
    lyrics: "https://www.youtube.com/watch?v=Gg6NMU4ivXM",
    chords: ["Em D C D", "G D Em D"],
    strumming: "D UDUD UDUD DU",
    img: "https://i.ytimg.com/vi/PkjnF_0YxNQ/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDuI0SRStxYOfmG9B5HDysfCbWF6Q",
  },
  {
    id: 13,
    title: "Tera Mera Rishta",
    url: "https://www.youtube.com/watch?v=Pz4c1N4PUb8&t=260s",
    lyrics: "https://www.youtube.com/watch?v=S8BHBts-rgk",
    chords: ["Em D C D"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/Pz4c1N4PUb8/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBZ3RNYYM8S-ZYT0Ho_6RX7NEYTTg",
  },
  {
    id: 14,
    title: "Haal Ae Dil",
    url: "https://www.youtube.com/watch?v=Htkwc5Vqj7o&t=368s",
    lyrics: "https://www.youtube.com/watch?v=acdKE2hja7w",
    chords: ["Am G F Em", "Am C G F Em"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/Htkwc5Vqj7o/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA7bQ7PYxkWdhsRGbg56M4tLs7DyA",
  },
  {
    id: 15,
    title: "Kabhi Jo Badal",
    url: "https://www.youtube.com/watch?v=wzVHPqKiQuI",
    lyrics: "https://www.youtube.com/watch?v=11uuhJBllOQ",
    chords: ["Cm A# G# A#", "Cm Gm A#", "Fm A# G#"],
    strumming: "DD UUD DDU",
    img: "https://i.ytimg.com/vi/wzVHPqKiQuI/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2GcMSVlpwqxFy5F6hDh3IZsPHQQ",
  },
  {
    id: 16,
    title: "Teri Saanson Mein",
    url: "https://www.youtube.com/watch?v=RbWBOvjcSiQ",
    lyrics: "https://www.youtube.com/watch?v=eidPTVEwtEI",
    chords: ["A#m G# F# G#/F"],
    strumming: "D UDUD UDUD DU",
    img: "https://i.ytimg.com/vi/RbWBOvjcSiQ/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBK-ce54NveRodJ0b56_hBbdHszLA",
  },
  {
    id: 17,
    title: "Chahun Main Ya Na",
    url: "https://www.youtube.com/watch?v=rGLPjnsJB5o",
    lyrics: "https://www.youtube.com/watch?v=V193pqMe_8k",
    chords: ["Am G F G", "C Am F G", "C Em F G C", "Am G F E"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/rGLPjnsJB5o/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAt8ypQGl3rGONkbpdpSnbzJoBhSA",
  },

  {
    id: 18,
    title: "Mujhko Barsaat Bana Lo",
    url: "https://www.youtube.com/watch?v=-c4kVcsHc1A",
    lyrics: "https://www.youtube.com/watch?v=q21aUQyFde8",
    chords: ["Bm G A Bm", "A G A G F#", "Bm G Bm G", "Bm D A G Bm"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/-c4kVcsHc1A/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB8jB_Fg1c51KyFQX0ywJV4TYVepg",
  },
  {
    id: 19,
    title: "Teri Yaadein",
    url: "https://www.youtube.com/watch?v=vRUhpLyT1h4",
    lyrics: "https://www.youtube.com/watch?v=wv63vXivpfk",
    chords: ["Am G F Am", "G Am G Am", "C G F E"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/vRUhpLyT1h4/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBSZP5fSRyktdhk1KoufSBFYnDYRA",
  },
  {
    id: 20,
    title: "Filhaal-2",
    url: "https://www.youtube.com/watch?v=NJHXCMtZbc0",
    lyrics: "https://www.youtube.com/watch?v=8OdJN0gy56M",
    chords: ["Am Dm G C"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/NJHXCMtZbc0/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBQJHghFQINJA7p4DMaGzhSeq84KQ",
  },
];
////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const songs2 = [
  {
    id: 21,
    title: "Teri meri kahaani",
    url: "https://www.youtube.com/watch?v=QpwPIOBDSjg",
    lyrics: "https://www.youtube.com/watch?v=hcJl3ovWsYg",
    chords: ["D#m G#m D#m G#m C#", "D#m B C#", "D#m C# B G#m", "F# A#m B C#"],
    strumming: "D UDUD UDU DUDU",
    img: "https://i.ytimg.com/vi/QpwPIOBDSjg/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB7RKaIw1L17kn4XJ5WNg0UawXLZg",
  },
  {
    id: 22,
    title: "Bekhayali",
    url: "https://www.youtube.com/watch?v=9H1-hENz5rs",
    lyrics: "https://www.youtube.com/watch?v=NO4BUCFJPqQ",
    chords: ["Am F G Em - Dm F Am Em", "Am G F G"],
    strumming: "D DUDU",
    img: "https://i.ytimg.com/vi/9H1-hENz5rs/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCqfryQEdbOLTsJYkYnUxonuTb2HQ",
  },
  {
    id: 23,
    title: "Milne Hai Mujhse Aayi",
    url: "https://www.youtube.com/watch?v=LDU_4CciboI",
    lyrics: "https://www.youtube.com/watch?v=VVFDArjvalE",
    chords: ["Bm A G F#", "D A G A", "Bm A G"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/LDU_4CciboI/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAIsKEYfeBAnxoVmovRC_ZNcqExag",
  },
  {
    id: 24,
    title: "Sun Raha Hai Na Tu - Capo 3rd",
    url: "https://www.youtube.com/watch?v=l8nap6LuT8k",
    lyrics: "https://www.youtube.com/watch?v=pyzjQz209Xo",
    chords: ["Am F G Em F ", "Am D Am D", "Am G F Dm C", "F G Em C", "Dm C-E"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/l8nap6LuT8k/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAungIj7noDuwJ3zoFX8qvPUschGQ",
  },
  // {
  //   id: 25,
  //   title: "Tujhe Kitna Chahne lage",
  //   url: "https://www.youtube.com/watch?v=LK7hhMgCTeA",
  //   lyrics: "https://www.youtube.com/watch?v=xroMi3fFjys",
  //   chords: ["E F# D#m G#m C#m F#"],
  //   strumming: "D D UDUD DDU",
  //   img: "https://i.ytimg.com/vi/LK7hhMgCTeA/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC8WGSVJDKV9zuB4utCbQtKr4vxfg",
  // },
  {
    id: 25,
    title: "Tujhe Kitna Chahne lage - Capo 3rd",
    url: "https://www.youtube.com/watch?v=-qgPY7dHDJQ",
    lyrics: "https://www.youtube.com/watch?v=xroMi3fFjys",
    chords: ["Am D C D G", "C D Em Bm C D Em "],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/-qgPY7dHDJQ/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBkz_F6jtYozSCICjrsshtJAL8piw",
  },
  {
    id: 26,
    title: "Bulleya",
    url: "https://www.youtube.com/watch?v=DKYKlgGO4mQ",
    lyrics: "https://www.youtube.com/watch?v=bFn62eG2WYA",
    chords: ["Dm Bb-Eb A ", "Dm Bb G C Bb-Dm"],
    strumming: "DDU UDU",
    img: "https://i.ytimg.com/vi/DKYKlgGO4mQ/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBRQIIAKAzlfW8WJgF_AKVGM81ObQ",
  },
  // {
  //   id: 27,
  //   title: "Har Kisi Ko Nahi Milta",
  //   url: "https://www.youtube.com/watch?v=Ypfk97taiKk&t=629s",
  //   lyrics: "https://www.youtube.com/watch?v=WtgGzgcNHNk",
  //   chords: ["A# D# A# D# G#-A# G# F# G#", "A# G# B A#-A# D# F# A#"],
  //   strumming: "D UDUD UDUD DU",
  //   img: "https://i.ytimg.com/vi/Ypfk97taiKk/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDEEr2IbuycMACCOXlffTkdche_xQ",
  // },
  // {
  //   id: 27,
  //   title: "Samjhawan",
  //   url: "https://www.youtube.com/watch?v=PUfizkTONV4&list=RDPUfizkTONV4&start_radio=1",
  //   lyrics: "https://www.youtube.com/watch?v=KCgYeFH78VA",
  //   chords: ["E A", "B E - C#m B A E A E", "E C#m A E", "A G#m A E"],
  //   strumming: "DCU UCU",
  //   img: "https://i.ytimg.com/vi/PUfizkTONV4/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAlDd3XL33GJO4WkIZ4xxmsZWwADw",
  // },
  {
    id: 27,
    title: "Chale Aana",
    url: "https://www.youtube.com/watch?v=YOtpk6bDqw4",
    lyrics: "https://www.youtube.com/watch?v=YN3enhDqHis",
    chords: ["F#m E D E", "F#m E C#m D - Bm E C#m D", "D C#m D E "],
    strumming: "D DUC D",
    img: "https://i.ytimg.com/vi/YOtpk6bDqw4/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDuwFDmiBTD3EASI8Uk6JVCGoUE-A",
  },
  {
    id: 28,
    title: "O Saki Saki",
    url: "https://www.youtube.com/watch?v=Yz2zuONh6Fs",
    lyrics: "https://www.youtube.com/watch?v=IyGDL1F0EeY",
    chords: ["Fm - F G# D#m A#m", "A#m F# D#m C#"],
    strumming: "D UDUD UDUD",
    img: "https://i.ytimg.com/vi/Yz2zuONh6Fs/hqdefault.jpg?sqp=-oaymwEpCPYBEIoBSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIFhACGAYgATgBQAE=&rs=AOn4CLCIfPM_LOOUDJup1uhXxU0pAE6t-g",
  },
  {
    id: 29,
    title: "Khamoshiyan",
    url: "https://www.youtube.com/watch?v=Te71caGBmUk",
    lyrics: "https://www.youtube.com/watch?v=qN88U6ZqR-4",
    chords: ["Dm F Am Gm", "Bb C A", "Bb C F AmDm", "Dm Gm C F"],
    strumming: "D DUDU",
    img: "https://i.ytimg.com/vi/Te71caGBmUk/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCD4NhIh1_CxSDSFYEvRNTMgG5xQg",
  },
  {
    id: 30,
    title: "Banjaara",
    url: "https://www.youtube.com/watch?v=h3f0-0ytzM4",
    lyrics: "https://www.youtube.com/watch?v=6qwect3_VSE",
    chords: ["C#m A B C#m", "E G#m A B E", "G# C#m A B C#m "],
    strumming: "DDU UDU",
    img: "https://i.ytimg.com/vi/h3f0-0ytzM4/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBvFVPBsZAHgiR_pudCGND4v6xJAg",
  },
  {
    id: 31,
    title: "Kesariya",
    url: "https://www.youtube.com/watch?v=E3XqfI_jmbM",
    lyrics: "https://www.youtube.com/watch?v=W1S9AbHpWFY",
    chords: ["C Em F G", "F C F C-G"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/E3XqfI_jmbM/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBfU7g0JfOZbRMHNq6BatRtPYqaMw",
  },
  {
    id: 32,
    title: "Dil Ko Karar Aaya - Capo 4th",
    url: "https://www.youtube.com/watch?v=87gv9coTbYo",
    lyrics: "https://www.youtube.com/watch?v=6UIWWu6lN6M",
    chords: ["Em G D C-D"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/87gv9coTbYo/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD9ag_g17bIMSbttMW6HzOgfQeQ5g",
  },
  {
    id: 33,
    title: "Baarish - Capo 3rd",
    url: "https://www.youtube.com/watch?v=9erEl9-sdOo",
    lyrics: "https://www.youtube.com/watch?v=Wvkdopf7R9U",
    chords: ["Em D Am Bm C", "Em D C B Em", "Bm A C D Em"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/9erEl9-sdOo/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCqOYVYSVzDtTFjjHJmWOI9qiqzQQ",
  },
  {
    id: 34,
    title: "Khairiyat - Capo 3rd",
    url: "https://www.youtube.com/watch?v=LUjx5vh5Id8",
    lyrics: "https://www.youtube.com/watch?v=wGAhDeobiac",
    chords: ["Am G F", "Am F G E", "Dm F G E", "C G E"],
    strumming: "DUCU UCU",
    img: "https://i.ytimg.com/vi/LUjx5vh5Id8/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCe0cbI1MvnbunDqT8KTyWUjo4uQQ",
  },

  {
    id: 35,
    title: "Jitni Dafa - Capo 1st",
    url: "https://www.youtube.com/watch?v=L7cgv9KDTaw",
    lyrics: "https://www.youtube.com/watch?v=x3DUuRw4hHI",
    chords: ["Am C G E-Am F G Am", "Am F C Dm G Am"],
    strumming: "DUCU UCU",
    img: "https://i.ytimg.com/vi/L7cgv9KDTaw/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAFSMxLFSBRKkCxtFzNQqAcvNicdw",
  },
  {
    id: 36,
    title: "Shayad - Capo 1st",
    url: "https://www.youtube.com/watch?v=d2u_TKR7btc",
    lyrics: "https://www.youtube.com/watch?v=A70-xPEYzww",
    chords: ["Em G D-Bm C G"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/d2u_TKR7btc/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBxhVf3bMTmUO6_f0uaZHpLicJ6iQ",
  },
  {
    id: 37,
    title: "Humnava Mere Capo - 1st",
    url: "https://www.youtube.com/watch?v=M7xe9JzLDkA",
    lyrics: "https://www.youtube.com/watch?v=aNot3gt_WJM",
    chords: ["Em D C D Em", "Em Am D-Bm", "Em D C Bm C D"],
    strumming: "D UCD UUC DU",
    img: "https://i.ytimg.com/vi/M7xe9JzLDkA/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBTJPF0W_hOBlfb4UA1TpkrbKVXiA",
  },
  {
    id: 38,
    title: "Janam Janam",
    url: "https://www.youtube.com/watch?v=5tDcfILfIA0",
    lyrics: "https://www.youtube.com/watch?v=g44iifQIFyM",
    chords: ["Bm Em A D G C F# G E F#"],
    strumming: "D DUDU",
    img: "https://i.ytimg.com/vi/UoF6pin59yc/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBWZbFoH1fBkh2W5ZkuS3Po3w29nw",
  },
  {
    id: 39,
    title: "Tum Hi Aana",
    url: "https://www.youtube.com/watch?v=aF3D7M0nsv0",
    lyrics: "https://www.youtube.com/watch?v=dnGPhxd4P4s",
    chords: ["C Em", "Em D Bm C", "D Am C Em"],
    strumming: "DUCU UCU",
    img: "https://i.ytimg.com/vi/aF3D7M0nsv0/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLArdju_w8j3oHn9YUB5S8hvHDEk3Q",
  },
  {
    id: 40,
    title: "Ye Jism Hai To Kya",
    url: "https://www.youtube.com/watch?v=iwSWMcyuiCw",
    lyrics: "https://www.youtube.com/watch?v=zApYIJfX3nk",
    chords: ["Em D C D C Em"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/iwSWMcyuiCw/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD3t_faohmJwO8mKVSDQk_X8V_vSQ",
  },
];
////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const songs3 = [
  // {
  //   id: 41,
  //   title: "Sajni",
  //   url: "https://www.youtube.com/watch?v=P1RwldegG_c&t=514s",
  //   lyrics: "https://www.youtube.com/watch?v=P1RwldegG_c&t=514s",
  //   chords: ["G#m F# C#m D#m", "E F# G#m"],
  //   strumming: "D UDUD UDUD DU",
  //   img: "https://i.ytimg.com/vi/P1RwldegG_c/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLADnxoqt2atJPmMMSbXa3BgA9K5Hw",
  // },
  {
    id: 41,
    title: "Pasoori",
    url: "https://www.youtube.com/watch?v=N5jkVcl85qY",
    lyrics: "https://www.youtube.com/watch?v=IV_JCpPe3SM",
    chords: [
      "Bm Bm A F#",
      "Bm D A Bm",
      "Bm A - G A F# Bm",
      "Em Bm A/F# Bm",
      "Em A D Em F# -Bm Em A D Bm",
      "A Bm F# Bm",
    ],
    strumming: `dud U du DU`,
    img: "https://i.ytimg.com/vi/N5jkVcl85qY/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLADAMH5oxlL0pbjBepvcWrdymnrsg",
  },
  {
    id: 42,
    title: "Labon Ko",
    url: "https://www.youtube.com/watch?v=cU3DMjFWqac",
    lyrics: "https://www.youtube.com/watch?v=0OGguI0uDfE",
    chords: ["Am G F", "E F G F G F", "Am G F G"],
    strumming: "D UDUD UDUD DU",
    img: "https://i.ytimg.com/vi/cU3DMjFWqac/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB_XpX9wilW6zX1N4E0Bq4YY5TzQg",
  },
  {
    id: 43,
    title: "Mile Ho Tum Humko",
    url: "https://www.youtube.com/watch?v=Du1XMsVasdE",
    lyrics: "https://www.youtube.com/watch?v=S6_xAEjBirw",
    chords: ["Am G F G Am -F Am Dm G F G Am"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/Du1XMsVasdE/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDkgVJZmrNSg71fjGRWGQgMo_U-Ug",
  },
  {
    id: 44,
    title: "Uska Hi Banana - Capo 3rd",
    url: "https://www.youtube.com/watch?v=jo5h47K-0EE",
    lyrics: "https://www.youtube.com/watch?v=x66LfjYJa2k",
    chords: ["Am G F E", "Am F G C", "Am Dm Em Am", "Am G F Em Am"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/jo5h47K-0EE/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBFrVUahQt56NrSJYf9fpqojGbcCA",
  },
  // {
  //   id: 45,
  //   title: "Phir Aur Kya Chahiye - Capo 4th",
  //   url: "https://www.youtube.com/watch?v=gd9d3tInXyI",
  //   lyrics: "https://www.youtube.com/watch?v=Lu7xpm2gtbA",
  //   chords: ["F G Am Dm F G Am"],
  //   strumming: "D D UDUD DDU",
  //   img: "https://i.ytimg.com/vi/gd9d3tInXyI/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC2mEB41Ho5ADhPWy94l0qHUmAmWA",
  // },
  {
    id: 45,
    title: "Pyar Hume - Capo 3rd",
    url: "https://www.youtube.com/watch?v=r8PkeaXYTiU",
    lyrics: "https://www.youtube.com/watch?v=0pU7hdlZvhQ",
    chords: ["Am F Dm Am", "Am G F G Am-Am Dm G Am", "Am C F G F Am"],
    strumming: "DDU UDU",
    img: "https://i.ytimg.com/vi/r8PkeaXYTiU/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDmyWWAn2RR1Qdbgo2KmuCqHCdlmA",
  },
  {
    id: 46,
    title: "Tera Hi Bas Hona Chaahoon Capo - 4th",
    url: "https://www.youtube.com/watch?v=0crddRPkw1s",
    lyrics: "https://www.youtube.com/watch?v=LiKzU6bmAcE",
    chords: ["Am G E Am", "Am G F E", "Am F Am", "C G F E"],
    strumming: "DD UUD DDU",
    img: "https://i.ytimg.com/vi/0crddRPkw1s/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAfHOgc2K2hXq4tYlpCpKa7zrJF1g",
  },
  {
    id: 47,
    title: "Mujhe Peene Do - Capo 6th",
    url: "https://www.youtube.com/watch?v=DayTEy1wlXU",
    lyrics: "https://www.youtube.com/watch?v=lIBDuC0jZSA",
    chords: ["Am G F E ", "Am C G E F-Dm G F Am"],
    strumming: "D DUDU",
    img: "https://i.ytimg.com/vi/DayTEy1wlXU/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD-ALlTX6pX9063SE0XxQW0z4WPPg",
  },
  {
    id: 48,
    title: "Bol Do Na Zara",
    url: "https://www.youtube.com/watch?v=YdZd9aohyYI",
    lyrics: "https://www.youtube.com/watch?v=f9_C8J4gqzQ",
    chords: ["Bm G F#m G", "Bm G Em A"],
    strumming: "D DUDU",
    img: "https://i.ytimg.com/vi/YdZd9aohyYI/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCPyQ0y4zQwCW1Qx0zt_3JH7swEAQ",
  },
  {
    id: 49,
    title: "Pee Loon",
    url: "https://www.youtube.com/watch?v=PtxFoiOezbc",
    lyrics: "https://www.youtube.com/watch?v=Nbr_KJT0TIc",
    chords: ["G# Fm G# - G# C# D#", "G# C# D# G#", "G# - Fm C# G#"],
    strumming: "DDU UDU",
    img: "https://i.ytimg.com/vi/PtxFoiOezbc/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC13MPtvql9AgGPK45Zz9UYEa06Dw",
  },

  {
    id: 50,
    title: "Jee Le Zara",
    url: "https://www.youtube.com/watch?v=DNOOevrC730",
    lyrics: "https://www.youtube.com/watch?v=NQncvPWen0o",
    chords: ["Am G-F Dm F G", "Am G F G Am"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/DNOOevrC730/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDItXEWjdDTmooIdVYIEgTsggxJ8w",
  },

  {
    id: 51,
    title: "Neele Neele Amber Par",
    url: "https://www.youtube.com/watch?v=76FHcjXavkA",
    lyrics: "https://www.youtube.com/watch?v=sXdG1SbRd3A",
    chords: ["C Dm ", "Dm C Bb A"],
    strumming: "DDU UDU",
    img: "https://i.ytimg.com/vi/76FHcjXavkA/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLAcZ_assNfBbCef7u3ZYeKiQOEC1A",
  },

  {
    id: 52,
    title: "Hai Apna Dil To Awara",
    url: "https://www.youtube.com/watch?v=IvDfwkGUErs&t=46s",
    lyrics: "https://www.youtube.com/watch?v=Qc0GYPXENms",
    chords: ["G DC DC DG", "G C D CG", "G G C DG"],
    strumming: "DUCUDUCU",
    img: "https://i.ytimg.com/vi/IvDfwkGUErs/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAfSQtugyjBDcRJleG_3WKbbYSuhw",
  },
  {
    id: 53,
    title: "Man Mera",
    url: "https://www.youtube.com/watch?v=Uo0sBQS1to8&t=26s",
    lyrics: "https://www.youtube.com/watch?v=s2kx8UOqFOs",
    chords: ["C#m B A B"],
    strumming: "D UUD UUD DU",
    img: "https://i.ytimg.com/vi/Uo0sBQS1to8/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDLMFvDDouDNoLjfkuEedjLMZuqFg",
  },
  {
    id: 54,
    title: "Main Dhoondne Ko Zamane Mein",
    url: "https://www.youtube.com/watch?v=iZDHhkCUcRA",
    lyrics: "https://www.youtube.com/watch?v=blkMNxQYCos",
    chords: ["Dm C Bb C"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/iZDHhkCUcRA/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCWVGLNwof7GPGc987fV0-jewpbyg",
  },
  {
    id: 55,
    title: "Hua Hai Aaj Pehli Baar",
    url: "https://www.youtube.com/watch?v=9l9WLZIjohY",
    lyrics: "https://www.youtube.com/watch?v=VCqWjVJxp2s",
    chords: ["F#m E D E  ", "F#m Bm E A D E C#m D", "F#m E C#m D-Bm C#m D-E "],
    strumming: "D DUC D",
    img: "https://i.ytimg.com/vi/9l9WLZIjohY/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBw9ZloRPTCVQFkAEBFyK3j9Vw4UA",
  },
  {
    id: 56,
    title: "Jannatein Kahan",
    url: "https://www.youtube.com/watch?v=foOy75Cl_uo",
    lyrics: "https://www.youtube.com/watch?v=po3xXqm2K14",
    chords: ["C Gm-A#", "C G Am F"],
    strumming: "D D D UDUD DUDU",
    img: "https://i.ytimg.com/vi/foOy75Cl_uo/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCf3u3WPiuphik_UMj_el617mFipQ",
  },
  // {
  //   id: 55,
  //   title: "Maan Meri Jaan - Capo 2nd",
  //   url: "https://www.youtube.com/watch?v=iFzpQngfWLk&t=168s",
  //   lyrics: "https://www.youtube.com/watch?v=3RAoczaBVP8",
  //   chords: ["G Em Am D"],
  //   strumming: "DDUC udu",
  //   img: "https://i.ytimg.com/vi/iFzpQngfWLk/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCJDnVuHJ8I4RqWTVWPZn5SzlHM8Q",
  // },
  // {
  //   id: 56,
  //   title: "Dil Mein Chupaa Loonga",
  //   url: "https://www.youtube.com/watch?v=iV67sFev4zI",
  //   lyrics: "https://www.youtube.com/watch?v=GW_PRQMzOEc",
  //   chords: ["F#m D A G/Em F#m", "D G F#m-F#m G F#m", "F#m A F#m G F#m"],
  //   strumming: "DDUC/D D UUD DDU",
  //   img: "https://i.ytimg.com/vi/iV67sFev4zI/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCAnx2JteuVhOSmEV2ayWRZx_e8Dw",
  // },
  {
    id: 57,
    title: "Hamari Adhuri Kahani",
    url: "https://www.youtube.com/watch?v=CvREKj8Evnc",
    lyrics: "https://www.youtube.com/watch?v=SRkfDLZxSww",
    chords: ["C F G/Bb C E", "Am F G C"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/CvREKj8Evnc/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLANnGrrj8jCK6wqxfyaqnJQ8vDanw",
  },
  {
    id: 58,
    title: "Tere Bin",
    url: "https://www.youtube.com/watch?v=Fqe1r3_RYws",
    lyrics: "https://www.youtube.com/watch?v=c6BuSdEE3kU",
    chords: ["Am Em F Em", "Am G F Am", "Am Gm G", "Am F G"],
    strumming: "D UUD UUD DU",
    img: "https://i.ytimg.com/vi/Fqe1r3_RYws/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCIGd_ke91xy75JscuoRDTVQM6HjQ",
  },
  {
    id: 59,
    title: "Tu Tu Hai Wahi",
    url: "https://www.youtube.com/watch?v=uz7EnyExVx8",
    lyrics: "https://www.youtube.com/watch?v=8tIufMKT9BI",
    chords: ["Em C D G Em D B Em", "Am C G Em-Em D Em"],
    strumming: "DDU UDU",
    img: "https://i.ytimg.com/vi/uz7EnyExVx8/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCSd6UTD4j_r6xok0GIFnAEFYCN0Q",
  },
  {
    id: 60,
    title: "Ya Ali",
    url: "https://www.youtube.com/watch?v=QB6lnNwVWZE",
    lyrics: "https://www.youtube.com/watch?v=sV562vmfzK8",
    chords: ["Em Am D B7 - D Em C B7", "Em Am C B7 "],
    strumming: "D U D U DUDU",
    img: "https://i.ytimg.com/vi/QB6lnNwVWZE/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDEqAQRHxy7UwLXlWs-88COgLcO7w",
  },
];
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const extras = [
  {
    id: 61,
    title: "3 Basic Finger Exercises",
    url: "https://www.youtube.com/watch?v=yoRg2fHQyLM",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/yoRg2fHQyLM/hqdefault.jpg?sqp=-oaymwEpCPYBEIoBSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIFhACGAYgATgBQAE=&rs=AOn4CLBojco9hn3KNQrmBfnLo3VN6Oagyg",
  },
  {
    id: 62,
    title: "Major Scales",
    url: "https://www.youtube.com/watch?v=iuWlJNswebA",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/iuWlJNswebA/hqdefault.jpg?sqp=-oaymwEpCPYBEIoBSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIFhACGAYgATgBQAE=&rs=AOn4CLAl5FxHrTrIbTXgmnrAdIFoXVM6Iw",
  },
  {
    id: 63,
    title: "Minor Scales",
    url: "https://www.youtube.com/watch?v=DnxrSf8STMU&t=141s",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/DnxrSf8STMU/hqdefault.jpg?sqp=-oaymwEpCPYBEIoBSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIFhACGAYgATgBQAE=&rs=AOn4CLDFWfYgtcNT5Y8V-Tfx_CwCVqFReQ",
  },
  {
    id: 64,
    title: "Tum Hi Ho - Lead",
    url: "https://www.youtube.com/watch?v=s2lvF0TrF2w",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/s2lvF0TrF2w/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDMxD8Ui8eReRos_1dPvVHG46PTmA",
  },
  {
    id: 65,
    title: "Kabhi Jo Badal - Lead",
    url: "https://www.youtube.com/watch?v=sUPIEnxEJb0",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/sUPIEnxEJb0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAOiwo6XRH8CZWN5A15SdiPF60PRw",
  },
  {
    id: 66,
    title: "Tujhe Kitna Chahein Aur Hum - Lead",
    url: "https://www.youtube.com/watch?v=6g2gyTLh7TY",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/6g2gyTLh7TY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBl4CyS5YT3_DqVPc1i0A2P4Q06lA",
  },
  {
    id: 67,
    title: "Filhaal 2 - Lead",
    url: "https://www.youtube.com/watch?v=jOuJWnsMDXM",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/jOuJWnsMDXM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAI_uzGKf803W6tv7VakVivIzSXKw",
  },
  {
    id: 68,
    title: "Shayad - Lead",
    url: "https://www.youtube.com/watch?v=3D4RHHsLK6M&t=149s",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/3D4RHHsLK6M/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCjzZt4D5cTDaXBZ-FJ2ftwn57aXA",
  },
  {
    id: 69,
    title: "Raataan Lambiyan - Lead",
    url: "https://www.youtube.com/watch?v=Muu8zEOfav4",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/Muu8zEOfav4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAFi8Nzp1t3-24tsBVl3k1fDg-sHw",
  },
  {
    id: 70,
    title: "Aadat - Lead",
    url: "https://www.youtube.com/watch?v=AqD56FWM7UQ",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/AqD56FWM7UQ/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAxIKECv5c7Yh7Upcj-mHfS14q1qA",
  },
  {
    id: 71,
    title: "1 Common Fingerstyle Pattern",
    url: "https://www.youtube.com/watch?v=WEkLeV-GOxI",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/WEkLeV-GOxI/hqdefault.jpg?sqp=-oaymwEpCPYBEIoBSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIFhACGAYgATgBQAE=&rs=AOn4CLB1BZYmKFSqwZCvFbxYlEClRqpg_w",
  },
  {
    id: 72,
    title: "Fingerstyle tutorial",
    url: "https://www.youtube.com/watch?v=rVPwdM_EEMM&t=3s",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/rVPwdM_EEMM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD523VIIOzvwCNPmwdE-RkSx3f3Dg",
  },
  // {
  //   id: 63,
  //   title: "Fingerstyle Exercise",
  //   url: "https://www.youtube.com/watch?v=znz6P3wkNP4&t=345s",
  //   lyrics: "",
  //   chords: [""],
  //   strumming: "",
  //   img: "https://i.ytimg.com/vi/znz6P3wkNP4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB_yea4uwKmeAsHHhHEXqRyw6rXGQ",
  // },
  // {
  //   id: 64,
  //   title: "Fingerstyle Alternative picking",
  //   url: "https://www.youtube.com/watch?v=MDu00TDO6AU",
  //   lyrics: "",
  //   chords: [""],
  //   strumming: "",
  //   img: "https://i.ytimg.com/vi/MDu00TDO6AU/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBgFpMriW0ziDjPV-pu8HBY9eLxsg",
  // },
  {
    id: 73,
    title: "Tum Hi Ho - Fingerstyle",
    url: "https://www.youtube.com/watch?v=2N0mflf2c0Q",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/2N0mflf2c0Q/hqdefault.jpg?sqp=-oaymwEpCPYBEIoBSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIFhACGAYgATgBQAE=&rs=AOn4CLCY6KEE-5nGDjNXRQ40PIhTUNuzUw",
  },
  {
    id: 74,
    title: "Khamoshiyan - Fingerstyle",
    url: "https://www.youtube.com/watch?v=FjfNRsJF7Nc",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/FjfNRsJF7Nc/hqdefault.jpg?sqp=-oaymwEpCPYBEIoBSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIFhACGAYgATgBQAE=&rs=AOn4CLBAn7T4QKNRampZ1LwDVtSgx5br_g",
  },
  {
    id: 75,
    title: "Pirates of Carribbean - Theme",
    url: "https://www.youtube.com/watch?v=-3euwoOoenM&t=80s",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/-3euwoOoenM/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAhUyid7G0ERoAbAUyZTT6BWE8nsg",
  },
  {
    id: 76,
    title: "Aadat - Fingerstyle",
    url: "https://www.youtube.com/watch?v=jF5u33x3DHA",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/jF5u33x3DHA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC9qEVYiQW-iJux3FHa4xi9VJvToQ",
  },
  {
    id: 77,
    title: "Gulabi Aankhein - Fingerstyle",
    url: "https://www.youtube.com/watch?v=-pcYxkitmkk&t=3s",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/-pcYxkitmkk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCUB4WxTw5CyfESCAwdFONaC4k1Lw",
  },
  {
    id: 78,
    title: "Amin Toofani - Veer Kumar",
    url: "https://www.youtube.com/watch?v=HG0BPP-aCq8",
    lyrics: "",
    chords: [""],
    strumming: "",
    img: "https://i.ytimg.com/vi/HG0BPP-aCq8/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDHFs8G5Uqpei7M_6s2VInpN9orlQ",
  },
  {
    id: 79,
    title: "Game of Thrones - Theme song",
    url: "https://www.youtube.com/watch?v=u_1fqr5OCMU&t=57s",
    lyrics: "",
    chords: [""],
    strumming: "D DUDU",
    img: "https://i.ytimg.com/vi/u_1fqr5OCMU/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLARv6FMNSLRDLRrkkRa6bWphmm7kQ",
  },
  {
    id: 80,
    title: "Hogaya Hai Tujhko - Capo 4th",
    url: "https://www.youtube.com/watch?v=yN-NYans-wA",
    lyrics: "https://www.youtube.com/watch?v=M_bBw50pRII",
    chords: ["Em C D B7 Em", "Em D Em-C Em", "Am Em-Em D Em"],
    strumming: "DDU/DU ",
    img: "https://i.ytimg.com/vi/yN-NYans-wA/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDEqc4NnA1pAXJz2Mqd8-QlVuQp2A",
  },
  {
    id: 81,
    title: "O O Jane Jana",
    url: "https://www.youtube.com/watch?v=kV2SK6M9VOg",
    lyrics: "https://www.youtube.com/watch?v=JtAp4GnkMbE",
    chords: ["Am G F G Em"],
    strumming: "D D UDUD DDU",
    img: "https://i.ytimg.com/vi/kV2SK6M9VOg/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBDyjbbERHKYRwmHYVM_jqpGKvm5Q",
  },
  {
    id: 82,
    title: "Filhaal - Capo 3rd",
    url: "https://www.youtube.com/watch?v=cEGGXdON28M&t=8s",
    lyrics: "https://www.youtube.com/watch?v=9Csrfj8QZN4",
    chords: ["F Em Am"],
    strumming: "D D UUD DDU",
    img: "https://i.ytimg.com/vi/cEGGXdON28M/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD9M2Djknr5U138H84onDGIu5K0Vw",
  },
  {
    id: 83,
    title: "Pani Da Rang",
    url: "https://www.youtube.com/watch?v=Qqm8xmgmlWc",
    lyrics: "https://www.youtube.com/watch?v=2kgEc6oH9J0",
    chords: ["Em D C D Em", "C D Em"],
    strumming: "D UUD UUD DU",
    img: "https://i.ytimg.com/vi/Qqm8xmgmlWc/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAfcmzL_18XC1GrLSi5Zra84yNS0w",
  },
  {
    id: 84,
    title: "Mere Mehboob Qayamat Hogi",
    url: "https://www.youtube.com/watch?v=nTxQJSUH2FY",
    lyrics: "https://www.youtube.com/watch?v=K9YWU0GB_es",
    chords: ["Bm A Em F#m G A Bm", "Bm-Em F#m Bm", "D A Em Bm A Bm"],
    strumming: "D DU UDU",
    img: "https://i.ytimg.com/vi/nTxQJSUH2FY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCiQ9Wt9yMN0jCore4rWQok-7HDsQ",
  },
  {
    id: 85,
    title: "Inteha Ho Gayi",
    url: "https://www.youtube.com/watch?v=1JbdMBNiw7I",
    lyrics: "https://www.youtube.com/watch?v=4muKrzVo7bU",
    chords: ["Em Am D F# B Em"],
    strumming: "D DU UDU",
    img: "https://i.ytimg.com/vi/1JbdMBNiw7I/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDn4-0qedGh3r-d96vKokCuSG1mXA",
  },
  {
    id: 86,
    title: "Change Strings on Guitar",
    url: "https://www.youtube.com/watch?v=XQKfpoCWol4&t=2s",
    lyrics: "",
    chords: [],
    strumming: "",
    img: "https://i.ytimg.com/vi/XQKfpoCWol4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAypIviilus7zVZBNkd9bDpvzEbJA",
  },
];
